project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/*",
    "translation": "/%language%/%original_file_name%",
    "update_option": "update_as_unapproved",
  }
]
